export const reviews = [
    {
      name: "Mwangi",
      username: "@mwangi",
      body: "I've never seen anything like this before. It's amazing. I love it.",
      img: "https://avatar.vercel.sh/mwangi",
    },
    {
      name: "Wanjiku",
      username: "@wanjiku",
      body: "I don't know what to say. I'm speechless. This is amazing.",
      img: "https://avatar.vercel.sh/wanjiku",
    },
    {
      name: "Otieno",
      username: "@otieno",
      body: "I'm at a loss for words. This is amazing. I love it.",
      img: "https://avatar.vercel.sh/otieno",
    },
    {
      name: "Akinyi",
      username: "@akinyi",
      body: "They understood exactly what I needed and delivered beyond expectations.",
      img: "https://avatar.vercel.sh/akinyi",
    },
    {
      name: "Kamau",
      username: "@kamau",
      body: "The professionalism and attention to detail are unmatched.",
      img: "https://avatar.vercel.sh/kamau",
    },
    {
      name: "Chebet",
      username: "@chebet",
      body: "Fast, reliable, and creative — the best tech experience I’ve had.",
      img: "https://avatar.vercel.sh/chebet",
    },
    {
      name: "Maina",
      username: "@maina",
      body: "They brought my idea to life in ways I couldn’t have imagined.",
      img: "https://avatar.vercel.sh/maina",
    },
    {
      name: "Njeri",
      username: "@njeri",
      body: "From start to finish, everything was smooth and transparent.",
      img: "https://avatar.vercel.sh/njeri",
    },
    {
      name: "Omondi",
      username: "@omondi",
      body: "Clear communication, timely delivery, and incredible results.",
      img: "https://avatar.vercel.sh/omondi",
    },
    {
      name: "Atieno",
      username: "@atieno",
      body: "They turned a complex project into something simple and beautiful.",
      img: "https://avatar.vercel.sh/atieno",
    },
    {
      name: "Mutua",
      username: "@mutua",
      body: "Every interaction felt personal and thoughtful.",
      img: "https://avatar.vercel.sh/mutua",
    },
    {
      name: "Makena",
      username: "@makena",
      body: "They go above and beyond every single time.",
      img: "https://avatar.vercel.sh/makena",
    },
    {
      name: "Baraka",
      username: "@baraka",
      body: "This is how tech services should be — professional and creative.",
      img: "https://avatar.vercel.sh/baraka",
    },
    {
      name: "Achieng",
      username: "@achieng",
      body: "Seamless process, excellent service, and perfect execution.",
      img: "https://avatar.vercel.sh/achieng",
    },
    {
      name: "Kiptoo",
      username: "@kiptoo",
      body: "They listen, adapt, and deliver beyond expectations.",
      img: "https://avatar.vercel.sh/kiptoo",
    },
    {
      name: "Mwende",
      username: "@mwende",
      body: "I recommend them to anyone who values quality and innovation.",
      img: "https://avatar.vercel.sh/mwende",
    },
    {
      name: "Cheruiyot",
      username: "@cheruiyot",
      body: "They took the time to understand my vision and nailed it.",
      img: "https://avatar.vercel.sh/cheruiyot",
    },
    {
      name: "Nyambura",
      username: "@nyambura",
      body: "True professionals with an eye for detail.",
      img: "https://avatar.vercel.sh/nyambura",
    },
    {
      name: "Kibet",
      username: "@kibet",
      body: "The final product was even better than I had hoped for.",
      img: "https://avatar.vercel.sh/kibet",
    },
    {
      name: "Wairimu",
      username: "@wairimu",
      body: "If you want results, this is the team you need.",
      img: "https://avatar.vercel.sh/wairimu",
    },
    {
      name: "Mutiso",
      username: "@mutiso",
      body: "A rare mix of skill, creativity, and reliability.",
      img: "https://avatar.vercel.sh/mutiso",
    },
    {
      name: "Nduta",
      username: "@nduta",
      body: "Their work speaks for itself — absolutely stunning.",
      img: "https://avatar.vercel.sh/nduta",
    },
    {
      name: "Karanja",
      username: "@karanja",
      body: "I will definitely work with them again.",
      img: "https://avatar.vercel.sh/karanja",
    },
    {
      name: "Mumbi",
      username: "@mumbi",
      body: "Everything was delivered on time and perfectly executed.",
      img: "https://avatar.vercel.sh/mumbi",
    },
    {
      name: "Wekesa",
      username: "@wekesa",
      body: "They make complicated things feel effortless.",
      img: "https://avatar.vercel.sh/wekesa",
    },
    {
      name: "Njoki",
      username: "@njoki",
      body: "One of the best decisions I’ve made was hiring them.",
      img: "https://avatar.vercel.sh/njoki",
    },
    {
      name: "Otis",
      username: "@otis",
      body: "They don’t just deliver projects, they deliver excellence.",
      img: "https://avatar.vercel.sh/otis",
    },
    {
      name: "Sharon",
      username: "@sharon",
      body: "From concept to completion, they were outstanding.",
      img: "https://avatar.vercel.sh/sharon",
    },
    {
      name: "Ndungu",
      username: "@ndungu",
      body: "A trustworthy team with exceptional skills.",
      img: "https://avatar.vercel.sh/ndungu",
    },
    {
      name: "Linet",
      username: "@linet",
      body: "They set the bar for what tech service should be.",
      img: "https://avatar.vercel.sh/linet",
    }
  ];
  